# Created with YamlCreate.ps1 v2.1.2 $debug=QUSU.7-2-6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: KDE.Okular
PackageVersion: 22.08.1
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://charlotte.kde.org/binary-factory/Okular_Release_win64/1143/okular-22.08.1-1143-windows-msvc2019_64-cl.exe
  InstallerSha256: B89051F9B59AB3198B57E45F0727507CB079FE903B291B1ECC9FC43F382B0252
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://charlotte.kde.org/binary-factory/Okular_Release_win64/1143/okular-22.08.1-1143-windows-msvc2019_64-cl.exe
  InstallerSha256: B89051F9B59AB3198B57E45F0727507CB079FE903B291B1ECC9FC43F382B0252
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.1.0
